<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="DotNetEnv" Version="3.1.1" />
      <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.9">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.9" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.9" />
      <PackageReference Include="Npgsql" Version="9.0.3" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
      <PackageReference Include="Quartz" Version="3.15.0" />
      <PackageReference Include="Quartz-Concurrent.Extensions.Hosting" Version="3.2.2-concurrent-v1.0.0" />
      <PackageReference Include="Quartz.Extensions.DependencyInjection" Version="3.15.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\EventMarketplace.Application\EventMarketplace.Application.csproj" />
      <ProjectReference Include="..\EventMarketplace.Domain\EventMarketplace.Domain.csproj" />
    </ItemGroup>

</Project>
